### ISSUE TITLE
Feature Request: Nextflow Language Formatter

### ISSUE THREAD

**Issue by LawrenceLiu023** [nextflow-io/vscode-language-nextflow#31]
Would it be possible to add a code formatter function for `.nf` and `nextflow.config` files? This would help keep Nextflow code consistently formatted and make it easier to read and maintain.
Currently, the only option is to use a Groovy language formatter, but the results are not ideal and do not fully accommodate the Nextflow DSL syntax. A Nextflow code formatter would be much more effective.
If this feature could be added, it would greatly enhance the Nextflow development experience. Please consider adding a Nextflow-specific code formatter. Thank you for your consideration!

**Comment by bentsherman** [comment]
Delivered in v1.0.0
