### ISSUE TITLE
Escaping environment variables in script section produces irregular results

### ISSUE THREAD

**Issue by kgalens** [nextflow-io/vscode-language-nextflow#36]
After formatting, the process file was formatted by removing the backslash added to bash environment variables.

**Before**:
![Screenshot 2024-10-29 at 13 40 38](https://github.com/user-attachments/assets/5630ca3c-e116-4f73-8c6c-942a76279165)

**After**:
![Screenshot 2024-10-29 at 13 40 47](https://github.com/user-attachments/assets/282b7a3c-bcf8-49aa-91a5-eb9d50435e21)

And then, only after a second save, it will wrap the variable in brackets:
![Screenshot 2024-10-29 at 13 41 02](https://github.com/user-attachments/assets/937c1afe-ace4-4904-b3d1-c313a31aa050)

After removing the escape sequence, it does correctly identify it as a missing variable.

**Comment by bentsherman** [comment]
Related to https://github.com/nextflow-io/language-server/issues/41
