### ISSUE TITLE
Unclear information on setting java path

### ISSUE THREAD

**Issue by fgroll** [nextflow-io/vscode-language-nextflow#49]
The extension couldn't find my installation of java, so I set `nextflow.java.home` in the settings to the path containing my java executable: `/conda_envs/nextflow/bin/`. But this returned the error: "The nextflow.java.home setting does not point to a valid JDK."
After looking at the code in `utils/findJava.ts` I saw that the final path is constructed as `path.join(settingsJavaHome, "bin", executableFile)`, adding a 'bin' to the end of the directory path set in `nextflow.java.home`. So instead of looking for the java executable in `/conda_envs/nextflow/bin/`, it was instead looking in `/conda_envs/nextflow/bin/bin/`.

The description in the settings states Java: Home "Specifies the folder path to the JDK.". To me this reads as it expects a directory that contains `java` directly, not `bin/java`.
I am not used to java at all, so I am not sure if that is the way it usually works in the java ecosystem, but I think it would be useful to clarify exactly what the path for `nextflow.java.home` should contain. Thank you!

**Comment by bentsherman** [comment]
Good point, the description will be improved in v1.0.1
