### ISSUE TITLE
Prevent evaluating subsets of code

### ISSUE THREAD

**Issue by risoms** [nextflow-io/vscode-language-nextflow#55]
Is it possible to comment a section of code, to not be evaluated by the Nextflow linter? This is in the same vein as the `#noqa` comment code to ignore Python PEP8 warnings?

**Comment by bentsherman** [comment]
There is no way to suppress things on specific lines

**Comment by bentsherman** [comment]
Can you give an example of a warning you'd like to suppress?

**Comment by bentsherman** [comment]
Closing in favor of https://github.com/nextflow-io/language-server/issues/75 and https://github.com/nextflow-io/language-server/issues/76
