### ISSUE TITLE
Error with optional output

### ISSUE THREAD

**Issue by phoenix-yyj** [nextflow-io/vscode-language-nextflow#57]
Nextflow doc says output in process can have the keywork `optional`

like:
```
output:
path("output.txt"), optional: true
```
it works well with `path`,but when come to `tuple`
```
output:
tuple(path("output.txt"),vale(meta)), optional: true
```
an error occured
```
Unexpected input: ','
```
however,as the doc's note says
> While this option can be used with any process output, it cannot be applied to individual elements of a [tuple](https://nextflow.io/docs/latest/process.html#output-tuples-tuple) output. The entire tuple must be optional or not optional.

is there anything i miss in doc?

**Comment by phoenix-yyj** [comment]
Sry for opin issue in a wrong repo. close it

**Comment by bentsherman** [comment]
no worries, I can always transfer the issue to the right repo
