### ISSUE TITLE
Spread operator highlighted as error

### ISSUE THREAD

**Issue by awgymer** [nextflow-io/vscode-language-nextflow#61]
I am finding that the `*` spread operator is highlighted by the plugin as an error. 

Is this disallowed/unadvised by the new restriction on groovy syntax or is this a bug:

```groovy
// Where ch_bams.tumour is:
// [id, meta, [bam, bai]]

ch_tumour_bams = ch_bams.tumour.map{ _id, meta, bambai -> [meta, *bambai]}
``` 

The `*` is underlined in red with the error: `Unexpected input: '*'nextflow`

Using v1.0.2 of the extension

**Comment by bentsherman** [comment]
The spread operator is no longer allowed in the strict syntax. It is sort of an anti-pattern but I can see why people use it. I intend to add a better syntax for bundling/unbundling tuples in the future.

**Comment by awgymer** [comment]
Can you recommend a better/right way to do this unpacking at the moment? 

Currently the error means that the whole flow of the language server extension is borked (it thinks it can't parse the subworkflow file and so none of the helpful tooltips or anything else in the file is highlighted)

**Comment by bentsherman** [comment]
You need to explicitly enumerate the nested tuple elements:
```groovy
ch_bams.tumour.map { _id, meta, bambai -> [meta, bambai[0], bambai[1]] }
```

You can also do this:
```groovy
ch_bams.tumour.map { _id, meta, bambai ->
  def (bam, bai) = bambai
  [meta, bam, bai]
}
```

In the future I want to find some way to get the best of both worlds, something like this:
```groovy
// theoretical
ch_bams.tumour.map { _id, meta, (bam, bai) -> [meta, bam, bai] }
```

**Comment by bentsherman** [comment]
Going to document this in the syntax docs shortly
