### ISSUE TITLE
Request to add the extension to the Open VSX Registry

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/vscode-language-nextflow#8]
Gitpod can only load extensions from the Open VSX registry. 

https://www.gitpod.io/docs/vscode-extensions#where-do-i-find-extensions

It would be nice if Nextflow syntax highlighting could also be used with VScode in Gitpod too.
The instructions are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Open VSX Registry: https://open-vsx.org/

**Comment by sjroth** [comment]
https://github.com/HaaLeo/publish-vscode-extension#readme

This could help with this effort.

**Comment by sjroth** [comment]
https://github.com/HaaLeo/publish-vscode-extension#readme

This could help with this effort.
