### ISSUE TITLE
Feature Request: beautify on save

### ISSUE THREAD

**Issue by plaquette** [nextflow-io/vscode-language-nextflow#9]
It would be extremely helpful to have a beautifier for nextflow that acts on save similar to [black](https://github.com/psf/black)

### Expected Behavior
On save long calls as:

`process_01(one_ch.first(), two.out.average_two.first(), three.out.file, four_ch, five_ch, six.out.files.flatten().collate(10))`

would be formatted in a more readable format similar to: 

    workflow {
    channel.from('Hello') \
      | map { it.reverse() } \
      | (foo & bar) \
      | mix \
      | view
    }

**Comment by Emiller88** [comment]
https://github.com/nf-core/prettier-plugin-nextflow

**Comment by Emiller88** [comment]
I think the end game is going to come from an LSP honestly https://github.com/nextflow-io/vscode-language-nextflow/pull/20
